gameshop/adminapp/urls.py
from django.urls import re_path
from .apps import AdminappConfig

import adminapp.views as adminapp

app_name = AdminappConfig.name

urlpatterns = [
    re_path(r"^$", adminapp.admin_main, name="admin_main"),

    re_path(r"^users/create/$", adminapp.user_create, name='user_create'),
    re_path(r"^users/read/$", adminapp.UsersListView.as_view(), name="users"),
    re_path(r"^users/update/(?P<pk>\d+)/$", adminapp.user_update, name='user_update'),
    re_path(r"^users/delete/(?P<pk>\d+)/$", adminapp.user_delete, name='user_delete'),

    re_path(r"^categories/create/$", adminapp.ProductCategoryCreateView.as_view(), name="category_create"),
    re_path(r"^categories/read/$", adminapp.categories, name='categories'),
    re_path(r"^categories/update/(?P<pk>\d+)/$", adminapp.ProductCategoryUpdateView.as_view(), name="category_update"),
    re_path(r"^categories/delete/(?P<pk>\d+)/$", adminapp.ProductCategoryDeleteView.as_view(), name="category_delete"),

    re_path(r"^products/create/category/(?P<pk>\d+)/$", adminapp.product_create, name='product_create'),
    re_path(r"^products/read/category/(?P<pk>\d+)/$", adminapp.products, name='products'),
    re_path(r"^products/read/category/(?P<pk>\d+)/page/(?P<page>\d+)/$", adminapp.products, name='page'),
    re_path(r"^products/read/(?P<pk>\d+)/$", adminapp.ProductDetailView.as_view(), name="product_read"),
    re_path(r"^products/update/(?P<pk>\d+)/$", adminapp.product_update, name='product_update'),
    re_path(r"^products/delete/(?P<pk>\d+)/$", adminapp.product_delete, name='product_delete'),
]

gameshop/authnapp/urls.py
from django.urls import re_path
from .apps import AuthnappConfig

import authnapp.views as authnapp

app_name = AuthnappConfig.name

urlpatterns = [
    re_path(r"^login/$", authnapp.login, name="login"),
    re_path(r"^logout/$", authnapp.logout, name="logout"),
    re_path(r"^register/$", authnapp.register, name="register"),
    re_path(r"^edit/$", authnapp.edit, name="edit"),
    re_path(r"^verify/(?P<email>.+)/(?P<activation_key>\w+)/$", authnapp.verify, name='verify'),
]

gameshop/basketapp/urls.py
from django.urls import re_path
from .apps import BasketappConfig

import basketapp.views as basketapp

app_name = BasketappConfig.name

urlpatterns = [
    re_path(r"^$", basketapp.basket, name="view"),
    re_path(r"^add/(?P<pk>\d+)/$", basketapp.basket_add, name="add"),
    re_path(r"^remove/(?P<pk>\d+)/$", basketapp.basket_remove, name="remove"),
    re_path(r"^edit/(?P<pk>\d+)/(?P<quantity>\d+)/$", basketapp.basket_edit, name="edit"),
]

gameshop/gameshop/urls.py
from django.conf import settings
from django.conf.urls import include
from django.urls import path, re_path
from django.conf.urls.static import static

import mainapp.views as mainapp

urlpatterns = [
    re_path(r"^admin/", include('adminapp.urls', namespace='admin')),
    re_path(r"^$", mainapp.main, name="main"),
    re_path(r"^playstation/", include('mainapp.urls', namespace='playstation')),
    re_path(r"^contact/", mainapp.contact, name="contact"),
    re_path(r"^auth/", include('authnapp.urls', namespace='auth')),
    re_path(r"^basket/", include('basketapp.urls', namespace='basket')),
    re_path(r"^order/", include('ordersapp.urls', namespace="order")),
    path("", include("social_django.urls", namespace="social"))
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [re_path(r"^__debug__/", include(debug_toolbar.urls))]

gameshop/mainapp/urls.py
from django.urls import re_path
from .apps import MainappConfig

import mainapp.views as mainapp

app_name = MainappConfig.name

urlpatterns = [
   re_path(r"^$", mainapp.playstation, name='index'),
   re_path(r"^game/(?P<pk>\d+)/$", mainapp.playstation, name='game'),
]

gameshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name="имя", max_length=64, unique=True)
    is_active = models.BooleanField(db_index=True, verbose_name='активна', default=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name="имя", max_length=100)
    publisher = models.CharField(verbose_name="издатель", max_length=100, blank=True)
    developer = models.CharField(verbose_name="разработчик", max_length=100, blank=True)
    released = models.CharField(verbose_name="дата выхода", max_length=10, blank=True)
    platform = models.CharField(verbose_name="платформа", max_length=20, default="PS4")
    genre = models.CharField(verbose_name="жанр", max_length=50, blank=True)
    language = models.CharField(verbose_name="язык", max_length=30, default="Русский")
    age = models.CharField(verbose_name="возрастной рейтинг", max_length=10, default="18+")
    image = models.ImageField(upload_to='products_images', blank=True)
    description = models.TextField(verbose_name="описание", blank=True)
    price = models.DecimalField(verbose_name="цена", max_digits=8, decimal_places=0, default=0)
    quantity = models.PositiveIntegerField(verbose_name="остаток на складе", default=0)
    image01 = models.ImageField(upload_to='products_images', blank=True)
    image02 = models.ImageField(upload_to='products_images', blank=True)
    image03 = models.ImageField(upload_to='products_images', blank=True)
    image04 = models.ImageField(upload_to='products_images', blank=True)
    image05 = models.ImageField(upload_to='products_images', blank=True)
    image06 = models.ImageField(upload_to='products_images', blank=True)
    video_url = models.TextField(verbose_name="ссылка на видео", blank=True)
    is_active = models.BooleanField(db_index=True, verbose_name='активна', default=True)

    def __str__(self):
        return self.name

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')


class Contact(models.Model):
    phone = models.CharField(max_length=50, verbose_name="номер телефона")
    email = models.EmailField(max_length=254, verbose_name="электронная почта")
    city = models.CharField(max_length=128, default="Краснодар", verbose_name="город")
    address = models.CharField(max_length=254, verbose_name="адресс")

    def __str__(self):
        return f"{self.pk} {self.email}"

gameshop/mainapp/views.py
from django.conf import settings
from django.shortcuts import get_object_or_404, render

from basketapp.models import Basket
from .models import Contact, Product, ProductCategory
from django.utils import timezone
import random
import datetime


def main(request):
    title = 'Главная'
    content = {'title': title,  "media_url": settings.MEDIA_URL}
    return render(request, 'mainapp/index.html', content)


def get_hot_product():
    products = Product.objects.all()
    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]
    return same_products


def playstation(request, pk=None):
    title = "PlayStation"

    if pk is not None:
        product = get_object_or_404(Product, pk=pk)
        same_products = Product.objects.filter(category=product.category).exclude(pk=product.pk)[:3]
        content = {
            "title": title,
            "product": product,
            "same_products": same_products,
            "media_url": settings.MEDIA_URL,
        }
        return render(request, "mainapp/game_list.html", content)

    hot_product = get_hot_product()

    categories = ProductCategory.objects.all()
    products = Product.objects.all()
    new_products = Product.objects.filter(category__pk=1)
    exclusive_products = Product.objects.filter(category__pk=2)
    cool_products = Product.objects.filter(category__pk=3)
    ubisoft_products = Product.objects.filter(category__pk=4)
    ea_products = Product.objects.filter(category__pk=5)
    content = {
        "title": title,
        "categories": categories,
        "products": products,
        "new_products": new_products,
        "exclusive_products": exclusive_products,
        "cool_products": cool_products,
        "ubisoft_products": ubisoft_products,
        "ea_products": ea_products,
        "hot_product": hot_product,
        "media_url": settings.MEDIA_URL,
    }

    if pk:
        print(f"User select category: {pk}")

    return render(request, "mainapp/playstation.html", content)


def game_list(request, pk=None):

    if pk is not None:
        title = "Игра для PlayStation"
        product = get_object_or_404(Product, pk=pk)

    content = {
        "product": product,
        "title": title,
        "media_url": settings.MEDIA_URL,
    }

    return render(request, "mainapp/game_list.html.html", content)


def contact(request):
    title = "О нас"
    visit_date = datetime.datetime.now()
    information = Contact.objects.all()
    content = {"title": title, "visit_date": visit_date, "information": information}
    return render(request, "mainapp/contact.html", content)

gameshop/mainapp/templates/mainapp/includes/inc_index_menu.html
{% load staticfiles %}

<ul class="index-menu">
    <li class="Menu-list"><a href="{% url 'main' %}" class="index-menu-link-active">Главная</a></li>
    <li class="Menu-list"><a href="{% url 'playstation:index' %}" class="index-menu-link">PlayStation</a></li>
    <li class="Menu-list"><a href="{% url 'contact' %}" class="index-menu-link">О нас</a></li>
    
    {% if user.is_authenticated %}
    <li class="Menu-list">
        <div class="dropdown">
            <a class="index-menu-link" href="" data-toggle="dropdown">
                {{ user.first_name|default:'Пользователь' }}
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                <li style="width: 100%;"><a href="{% url 'auth:edit' %}" style="text-align: center;">Профиль</a></li>
                <li style="width: 100%;"><a href="{% url 'ordersapp:orders_list' %}" style="text-align: center;">Заказы</a></li>
            </ul>
        </div>
    </li>
    {% endif %}
    {% if user.is_superuser %}
    <li class="Menu-list">
        <a href="{% url 'admin:users' %}" class="index-menu-link">Админка</a>
    </li>
    {% endif %}
    <li class="Menu-list">
        {% if user.is_authenticated %}
        <a href="{% url 'auth:logout' %}" class="index-menu-link">Выйти</a>
        {% else %}
        <a href="{% url 'auth:login' %}" class="index-menu-link">Войти</a>
        {% endif %}
    </li>
    <a href="#" class="search"></a>
    <a href="{% url 'basket:view' %}" class="basket-index-span">
        <img src="{% static 'img/basket.png' %}">
        <span>
            {% if basket %} 
                {{ basket.0.total_cost|floatformat:0 }} ₽ ({{ basket.0.total_quantity }} товар)
            {% endif %}
        </span>
    </a>
</ul>

gameshop/mainapp/templates/mainapp/includes/inc_menu.html
{% load staticfiles %}

<ul class="Menu">
    <li class="Menu-list">
        <a href="{% url 'main' %}" class="{% if request.resolver_match.url_name == 'main' %}Menu-link-active{% endif %}">
            Главная
        </a>
    </li>
    <li class="Menu-list">
        <a href="{% url 'playstation:index' %}"
            class="{% if request.resolver_match.url_name == 'index' %}Menu-link-active{% endif %}">
            PlayStation
        </a>
    </li>
    <li class="Menu-list">
        <a href="{% url 'contact' %}" class="{% if request.resolver_match.url_name == 'contact' %}Menu-link-active{% endif %}">
            О нас
        </a>
    </li>
    {% if user.is_authenticated %}
    <li class="Menu-list">
        <div class="dropdown">
            <a class="dropdown-toggle" href="" data-toggle="dropdown">
                {{ user.first_name|default:'Пользователь' }}
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                <li style="width: 100%;"><a href="{% url 'auth:edit' %}" style="text-align: center;">Профиль</a></li>
                <li style="width: 100%;"><a href="{% url 'ordersapp:orders_list' %}" style="text-align: center;">Заказы</a></li>
            </ul>
        </div>
    </li>
    {% endif %}
    <li class="Menu-list">
        {% if user.is_authenticated %}
        <a href="{% url 'auth:logout' %}">выйти</a>
        {% else %}
        <a href="{% url 'auth:login' %}">войти</a>
        {% endif %}
    </li>
    {% if user.is_superuser %}
    <li class="Menu-list">
        <a href="{% url 'admin:users' %}">Админка</a>
    </li>
    {% endif %}
    <a href="#" class="search"></a>
    <a href="{% url 'basket:view' %}" class="basket">
        <img src="{% static 'img/basket.png' %}">
        <span>
            {% if basket %} 
                {{ basket.0.total_cost|floatformat:0 }} ₽ ({{ basket.0.total_quantity }} товар)
            {% endif %}
        </span>
    </a>
</ul>