gameshop/basketapp/urls.py
from django.urls import re_path
from .apps import BasketappConfig

import basketapp.views as basketapp

app_name = BasketappConfig.name

urlpatterns = [
    re_path(r"^$", basketapp.basket, name="view"),
    re_path(r"^add/(?P<pk>\d+)/$", basketapp.basket_add, name="add"),
    re_path(r"^remove/(?P<pk>\d+)/$", basketapp.basket_remove, name="remove"),
    re_path(r"^edit/(?P<pk>\d+)/(?P<quantity>\d+)/$", basketapp.basket_edit, name="edit"),
]

gameshop/gameshop/urls.py
from django.conf import settings
from django.conf.urls import include
from django.urls import path, re_path
from django.conf.urls.static import static

import mainapp.views as mainapp

urlpatterns = [
    re_path(r"^admin/", include('adminapp.urls', namespace='admin')),
    re_path(r"^$", mainapp.main, name="main"),
    re_path(r"^playstation/", include('mainapp.urls', namespace='playstation')),
    re_path(r"^contact/", mainapp.contact, name="contact"),
    re_path(r"^auth/", include('authnapp.urls', namespace='auth')),
    re_path(r"^basket/", include('basketapp.urls', namespace='basket')),
    re_path(r"^order/", include('ordersapp.urls', namespace="order")),
    path("", include("social_django.urls", namespace="social"))
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [re_path(r"^__debug__/", include(debug_toolbar.urls))]

gameshop/mainapp/urls.py
from django.urls import re_path
from .apps import MainappConfig

import mainapp.views as mainapp

app_name = MainappConfig.name

urlpatterns = [
   re_path(r"^$", mainapp.playstation, name='index'),
   re_path(r"^game/(?P<pk>\d+)/$", mainapp.playstation, name='game'),
]

gameshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name="имя", max_length=64, unique=True)
    is_active = models.BooleanField(db_index=True, verbose_name='активна', default=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name="имя", max_length=100)
    publisher = models.CharField(verbose_name="издатель", max_length=100, blank=True)
    developer = models.CharField(verbose_name="разработчик", max_length=100, blank=True)
    released = models.CharField(verbose_name="дата выхода", max_length=10, blank=True)
    platform = models.CharField(verbose_name="платформа", max_length=20, default="PS4")
    genre = models.CharField(verbose_name="жанр", max_length=50, blank=True)
    language = models.CharField(verbose_name="язык", max_length=30, default="Русский")
    age = models.CharField(verbose_name="возрастной рейтинг", max_length=10, default="18+")
    image = models.ImageField(upload_to='products_images', blank=True)
    description = models.TextField(verbose_name="описание", blank=True)
    price = models.DecimalField(verbose_name="цена", max_digits=8, decimal_places=0, default=0)
    quantity = models.PositiveIntegerField(verbose_name="остаток на складе", default=0)
    image01 = models.ImageField(upload_to='products_images', blank=True)
    image02 = models.ImageField(upload_to='products_images', blank=True)
    image03 = models.ImageField(upload_to='products_images', blank=True)
    image04 = models.ImageField(upload_to='products_images', blank=True)
    image05 = models.ImageField(upload_to='products_images', blank=True)
    image06 = models.ImageField(upload_to='products_images', blank=True)
    video_url = models.TextField(verbose_name="ссылка на видео", blank=True)
    is_active = models.BooleanField(db_index=True, verbose_name='активна', default=True)

    def __str__(self):
        return self.name

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')


class Contact(models.Model):
    phone = models.CharField(max_length=50, verbose_name="номер телефона")
    email = models.EmailField(max_length=254, verbose_name="электронная почта")
    city = models.CharField(max_length=128, default="Краснодар", verbose_name="город")
    address = models.CharField(max_length=254, verbose_name="адресс")

    def __str__(self):
        return f"{self.pk} {self.email}"

gameshop/mainapp/views.py
from django.conf import settings
from django.shortcuts import get_object_or_404, render

from basketapp.models import Basket
from .models import Contact, Product, ProductCategory
from django.utils import timezone
import random
import datetime


def main(request):
    title = 'Главная'
    content = {'title': title,  "media_url": settings.MEDIA_URL}
    return render(request, 'mainapp/index.html', content)


def get_hot_product():
    products = Product.objects.all()
    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(category=hot_product.category).exclude(pk=hot_product.pk)[:3]
    return same_products


def playstation(request, pk=None):
    title = "PlayStation"

    if pk is not None:
        product = get_object_or_404(Product, pk=pk)
        same_products = Product.objects.filter(category=product.category).exclude(pk=product.pk)[:3]
        content = {
            "title": title,
            "product": product,
            "same_products": same_products,
            "media_url": settings.MEDIA_URL,
        }
        return render(request, "mainapp/game_list.html", content)

    hot_product = get_hot_product()

    categories = ProductCategory.objects.all()
    products = Product.objects.all()
    new_products = Product.objects.filter(category__pk=1)
    exclusive_products = Product.objects.filter(category__pk=2)
    cool_products = Product.objects.filter(category__pk=3)
    ubisoft_products = Product.objects.filter(category__pk=4)
    ea_products = Product.objects.filter(category__pk=5)
    content = {
        "title": title,
        "categories": categories,
        "products": products,
        "new_products": new_products,
        "exclusive_products": exclusive_products,
        "cool_products": cool_products,
        "ubisoft_products": ubisoft_products,
        "ea_products": ea_products,
        "hot_product": hot_product,
        "media_url": settings.MEDIA_URL,
    }

    if pk:
        print(f"User select category: {pk}")

    return render(request, "mainapp/playstation.html", content)


def game_list(request, pk=None):

    if pk is not None:
        title = "Игра для PlayStation"
        product = get_object_or_404(Product, pk=pk)

    content = {
        "product": product,
        "title": title,
        "media_url": settings.MEDIA_URL,
    }

    return render(request, "mainapp/game_list.html.html", content)


def contact(request):
    title = "О нас"
    visit_date = datetime.datetime.now()
    information = Contact.objects.all()
    content = {"title": title, "visit_date": visit_date, "information": information}
    return render(request, "mainapp/contact.html", content)

gameshop/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title|capfirst }}
        {% endblock %}
    </title>
    
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    {% endblock %}

    {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>   
    {% endblock %}
</head>

<body>
	                   
    {% block menu %}
 
    {% endblock %}
    	

    {% block content %}

    {% endblock %}

    
    {% block footer %}

    <div class="footer">
        <p class="small">Все права защищены &copy; Andrew Ablezgov</p>               
        <p class="small">&copy; TopGames_KRD {% now "Y" %}</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        
    </div>

    {% endblock %}
	
</body>
</html>

gameshop/mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block menu %}
<div class="Container">
        <div class="Header">
            <p class="Logo-black">Top Games KRD</p> 
			{% include 'mainapp/includes/inc_menu.html' %}
		</div>
</div>

{% endblock %}
		
	
{% block content %}
	
<div class="Delivery">
	<div class="hero">
		<h1>Доставка&nbsp;и&nbsp;оплата</h1>
		<p>сегодня: {{ visit_date|date:"l, j F, Y" }}</p>
	</div>
	<div class="location">
		{% for info in information %}
		<div class="location-1">
			
			<i class="fa fa-map-marker fa-5x"></i>
			<h4>{{ info.city }}</h4>
			<div class="contacts">
				<h5>Телефон:</h5>
				<p>{{ info.phone }}</p><br>
				<h5>Email:</h5>
				<p>{{ info.email }}</p><br>
				<h5>Адрес:</h5>
				<p>{{ info.address }}</p>
			</div>
		</div>
		{% endfor %}		
	</div>
</div>

{% endblock %}

gameshop/mainapp/templates/mainapp/game_list.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block menu %}
<div class="Container">
        <div class="Header">
            <p class="Logo-black">Top Games KRD</p> 
			{% include 'mainapp/includes/inc_menu.html' %}
		</div>
</div>

{% endblock %}

{% block content %}

	<div class="GameHeader">
		<div class="left"> {{ product.name }}</div>
		<div class="right">Каталог >> Игры >> {{ product.name }}</div>
	</div>

	<div class="GameReview">

		<a href="{{ media_url }}{{ product.image }}" class="Gameimage-link"><img src = "{{ media_url }}{{ product.image }}" class="Gameimage"></a>
		
		<div>
			<p class="Game-H1">{{ product.name }}</p>
			<ul>
				<li><b>Издатель:</b> {{ product.publisher }}</li>
				<li><b>Разработчик:</b> {{ product.developer }}</li>
				<li><b>Дата выхода:</b> {{ product.released }}</li>
				<li><b>Платформа:</b> {{ product.platform }}</li>
				<li><b>Жанр:</b> {{ product.genre }}</li>
				<li><b>Язык:</b> {{ product.language }}</li>
				<li><b>Возрастной рейтинг:</b> {{ product.age }}</li>
			</ul>
			<p class="Game-H1">₽ {{ product.price }}</p>
			<a href="{% url 'basket:add' product.pk %}" class="GamePriceButton-link">Заказать</a>
		</div>
		<iframe class="Gamevideo" src="{{ product.video_url }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

	</div>

	<div class="GameFeatures">
        {{ product.description }} 
      </div>

      <div class="Describe">
        <table class="GameImages">
            <tr>
              <td class="GameImages-cells"><a href="{{ media_url }}{{ product.image01 }}"><img src = "{{ media_url }}{{ product.image01 }}"></a></td>
              <td class="GameImages-cells"><a href="{{ media_url }}{{ product.image02 }}"><img src = "{{ media_url }}{{ product.image02 }}"></a></td>
              <td class="GameImages-cells"><a href="{{ media_url }}{{ product.image03 }}"><img src = "{{ media_url }}{{ product.image03 }}"></a></td>
            </tr>
            <tr>
              <td class="GameImages-cells"><a href="{{ media_url }}{{ product.image04 }}"><img src = "{{ media_url }}{{ product.image04 }}"></a></td>
              <td class="GameImages-cells"><a href="{{ media_url }}{{ product.image05 }}"><img src = "{{ media_url }}{{ product.image05 }}"></a></td>
              <td class="GameImages-cells"><a href="{{ media_url }}{{ product.image06 }}"><img src = "{{ media_url }}{{ product.image06 }}"></a></td>
            </tr>
        </table>       
      </div>

	<div class="Catalog">
		<h2>Товары, похожие на этот</h2>
		{% for product in same_products %}
		<div class="product-wrap">
			<div class="product-item">
	    		<a href="{% url 'playstation:game' product.pk %}"><img src="{{ media_url }}{{ product.image }}" class="Catalog-image"></a>
	  		</div>
	  		<div class="product-title">
	    		<a href="{% url 'playstation:game' product.pk %}" class="product-title-link">{{ product.name }}</a>
	    		<span class="product-price">₽ {{ product.price}}</span>
	 		</div>
		</div>
		{% endfor %}
	</div>

{% endblock %}

gameshop/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block menu %}
<div class="Index">
	    <div class="index-header">
			<p class="index-logo">Top Games KRD</p>
			{% include 'mainapp/includes/inc_index_menu.html' %}
		</div>
		<video loop="" muted="" autoplay="" poster="{% static 'img/nioh2.jpg' %}" class="Background-video">
	        <source src="{% static 'img/nioh.mp4' %}" type="video/mp4">
	    </video>
</div>

{% endblock %}

gameshop/mainapp/templates/mainapp/playstation.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block menu %}
<div class="Container">
        <div class="Header">
            <p class="Logo-black">Top Games KRD</p> 
			{% include 'mainapp/includes/inc_menu.html' %}
		</div>
</div>
{% endblock %}

{% block content %}

	<div class="details-products">
	    <div class="details-slider">
	        <div class="slider-product">
	          <a href="{% url 'playstation:game' hot_product.pk %}"><img src="/media/{{ hot_product.image }}"></a>
	        </div>  
	    </div>

	    <div class="description">
	        <h3 class="big-bold">{{ hot_product.name }}</h3>
	        <h3 class="yellow">горячее предложение</h3>
	        <p class="price">{{ hot_product.price }} <span>₽</span></p>
	        <a href="{% url 'basket:add' hot_product.pk %}" class="HotGamePriceButton-link">
	          заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
	        </a>
	        <div class="description-text">
	          {{ hot_product.description }} 
	        </div>
	    </div>	    
	</div>

	<div class="GameHeader">		
		<div class="left">{{ categories.0.name }}</div>
	</div>

	<div class="Catalog">
		{% for product in new_products %}
		<div class="product-wrap">
			<div class="product-item">
	    		<a href="{% url 'playstation:game' product.pk %}"><img src="{{ media_url }}{{ product.image }}" class="Catalog-image"></a>
	  		</div>
	  		<div class="product-title">
	    		<a href="{% url 'playstation:game' product.pk %}" class="product-title-link">{{ product.name }}</a>
	    		<span class="product-price">₽ {{ product.price}}</span>
	 		</div>
		</div>
		{% endfor %}
	</div>

	<div class="GameHeader">		
		<div class="left">{{ categories.1.name }}</div>
	</div>

	<div class="Catalog">
		{% for product in exclusive_products %}
		<div class="product-wrap">
			<div class="product-item">
	    		<a href="{% url 'playstation:game' product.pk %}"><img src="{{ media_url }}{{ product.image }}" class="Catalog-image"></a>
	  		</div>
	  		<div class="product-title">
	    		<a href="{% url 'playstation:game' product.pk %}" class="product-title-link">{{ product.name }}</a>
	    		<span class="product-price">₽ {{ product.price}}</span>
	 		</div>
		</div>
		{% endfor %}
	</div>

	<div class="GameHeader">		
		<div class="left">{{ categories.2.name }}</div>
	</div>

	<div class="Catalog">
		{% for product in cool_products %}
		<div class="product-wrap">
			<div class="product-item">
	    		<a href="{% url 'playstation:game' product.pk %}"><img src="{{ media_url }}{{ product.image }}" class="Catalog-image"></a>
	  		</div>
	  		<div class="product-title">
	    		<a href="{% url 'playstation:game' product.pk %}" class="product-title-link">{{ product.name }}</a>
	    		<span class="product-price">₽ {{ product.price}}</span>
	 		</div>
		</div>
		{% endfor %}
	</div>

	<div class="GameHeader">		
		<div class="left">{{ categories.3.name }}</div>
	</div>

	<div class="Catalog">
		{% for product in ubisoft_products %}
		<div class="product-wrap">
			<div class="product-item">
	    		<a href="{% url 'playstation:game' product.pk %}"><img src="{{ media_url }}{{ product.image }}" class="Catalog-image"></a>
	  		</div>
	  		<div class="product-title">
	    		<a href="{% url 'playstation:game' product.pk %}" class="product-title-link">{{ product.name }}</a>
	    		<span class="product-price">₽ {{ product.price}}</span>
	 		</div>
		</div>
		{% endfor %}
	</div>

	<div class="GameHeader">		
		<div class="left">{{ categories.4.name }}</div>
	</div>
	<div class="Catalog">
		{% for product in ea_products %}
		<div class="product-wrap">
			<div class="product-item">
	    		<a href="{% url 'playstation:game' product.pk %}"><img src="{{ media_url }}{{ product.image }}" class="Catalog-image"></a>
	  		</div>
	  		<div class="product-title">
	    		<a href="{% url 'playstation:game' product.pk %}" class="product-title-link">{{ product.name }}</a>
	    		<span class="product-price">₽ {{ product.price}}</span>
	 		</div>
		</div>
		{% endfor %}
	</div>	

{% endblock %}