gameshop/adminapp/urls.py
from django.urls import re_path
from .apps import AdminappConfig

import adminapp.views as adminapp

app_name = AdminappConfig.name

urlpatterns = [
    re_path(r"^$", adminapp.admin_main, name="admin_main"),

    re_path(r"^users/create/$", adminapp.user_create, name='user_create'),
    re_path(r"^users/read/$", adminapp.UsersListView.as_view(), name="users"),
    re_path(r"^users/update/(?P<pk>\d+)/$", adminapp.user_update, name='user_update'),
    re_path(r"^users/delete/(?P<pk>\d+)/$", adminapp.user_delete, name='user_delete'),

    re_path(r"^categories/create/$", adminapp.ProductCategoryCreateView.as_view(), name="category_create"),
    re_path(r"^categories/read/$", adminapp.categories, name='categories'),
    re_path(r"^categories/update/(?P<pk>\d+)/$", adminapp.ProductCategoryUpdateView.as_view(), name="category_update"),
    re_path(r"^categories/delete/(?P<pk>\d+)/$", adminapp.ProductCategoryDeleteView.as_view(), name="category_delete"),

    re_path(r"^products/create/category/(?P<pk>\d+)/$", adminapp.product_create, name='product_create'),
    re_path(r"^products/read/category/(?P<pk>\d+)/$", adminapp.products, name='products'),
    re_path(r"^products/read/category/(?P<pk>\d+)/page/(?P<page>\d+)/$", adminapp.products, name='page'),
    re_path(r"^products/read/(?P<pk>\d+)/$", adminapp.ProductDetailView.as_view(), name="product_read"),
    re_path(r"^products/update/(?P<pk>\d+)/$", adminapp.product_update, name='product_update'),
    re_path(r"^products/delete/(?P<pk>\d+)/$", adminapp.product_delete, name='product_delete'),
]

gameshop/gameshop/urls.py
from django.conf import settings
from django.conf.urls import include
from django.urls import path, re_path
from django.conf.urls.static import static

import mainapp.views as mainapp

urlpatterns = [
    re_path(r"^admin/", include('adminapp.urls', namespace='admin')),
    re_path(r"^$", mainapp.main, name="main"),
    re_path(r"^playstation/", include('mainapp.urls', namespace='playstation')),
    re_path(r"^contact/", mainapp.contact, name="contact"),
    re_path(r"^auth/", include('authnapp.urls', namespace='auth')),
    re_path(r"^basket/", include('basketapp.urls', namespace='basket')),
    re_path(r"^order/", include('ordersapp.urls', namespace="order")),
    path("", include("social_django.urls", namespace="social"))
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [re_path(r"^__debug__/", include(debug_toolbar.urls))]

gameshop/mainapp/urls.py
from django.urls import re_path
from .apps import MainappConfig

import mainapp.views as mainapp

app_name = MainappConfig.name

urlpatterns = [
   re_path(r"^$", mainapp.playstation, name='index'),
   re_path(r"^game/(?P<pk>\d+)/$", mainapp.playstation, name='game'),
]

gameshop/adminapp/models.py
from django.db import models

gameshop/adminapp/forms.py
from django import forms

from authnapp.forms import ShopUserEditForm
from authnapp.models import ShopUser
from mainapp.models import ProductCategory, Product


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = "__all__"


class ProductCategoryEditForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
            field.help_text = ""

    class Meta:
        model = ProductCategory
        fields = "__all__"


class ProductEditForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

    class Meta:
        model = Product
        fields = '__all__'

gameshop/adminapp/views.py
from django.shortcuts import HttpResponseRedirect, get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.conf import settings
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView
from django.utils.decorators import method_decorator

from authnapp.forms import ShopUserRegisterForm
from authnapp.models import ShopUser
from adminapp.forms import ProductEditForm, ProductCategoryEditForm, ShopUserAdminEditForm
from mainapp.models import Product, ProductCategory


@user_passes_test(lambda u: u.is_superuser)
def admin_main(request):
    response = redirect("admin:users")
    return response


class UsersListView(LoginRequiredMixin, ListView):
    model = ShopUser
    template_name = "adminapp/users.html"


@user_passes_test(lambda u: u.is_superuser)
def user_create(request):
    title = "Создание нового пользователя"

    if request.method == 'POST':
        user_form = ShopUserRegisterForm(request.POST, request.FILES)
        if user_form.is_valid():
            user_form.save()
            return HttpResponseRedirect(reverse('admin:users'))
    else:
        user_form = ShopUserRegisterForm()

    content = {'title': title, 'update_form': user_form}

    return render(request, 'adminapp/user_update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def user_update(request, pk):
    title = "Редактирование пользователя"

    edit_user = get_object_or_404(ShopUser, pk=pk)
    if request.method == 'POST':
        edit_form = ShopUserAdminEditForm(request.POST, request.FILES, instance=edit_user)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse('admin:user_update', args=[edit_user.pk]))
    else:
        edit_form = ShopUserAdminEditForm(instance=edit_user)

    content = {'title': title, 'update_form': edit_form}

    return render(request, 'adminapp/user_update.html', content)


@user_passes_test(lambda u: u.is_superuser)
def user_delete(request, pk):
    title = "Удаление пользователя"

    user = get_object_or_404(ShopUser, pk=pk)

    if request.method == 'POST':
        user.is_active = False
        user.save()
        return HttpResponseRedirect(reverse('admin:users'))

    content = {'title': title, 'user_to_delete': user}

    return render(request, 'adminapp/user_delete.html', content)


@user_passes_test(lambda u: u.is_superuser)
def categories(request):
    title = "Категории"

    categories_list = ProductCategory.objects.all()

    content = {
        "title": title,
        "categories": categories_list,
        "media_url": settings.MEDIA_URL,
    }

    return render(request, 'adminapp/categories.html', content)


class ProductCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ProductCategory
    template_name = "adminapp/category_update.html"
    success_url = reverse_lazy("admin:categories")
    fields = "__all__"


class ProductCategoryUpdateView(LoginRequiredMixin, UpdateView):
    model = ProductCategory
    template_name = "adminapp/category_update.html"
    success_url = reverse_lazy("admin:categories")
    fields = "__all__"
    foo = "bar"

    def get_context_data(self, **kwargs):
        context = super(ProductCategoryUpdateView, self).get_context_data(**kwargs)
        context["title"] = "категории/редактирование"
        return context


class ProductCategoryDeleteView(LoginRequiredMixin, DeleteView):
    model = ProductCategory
    template_name = "adminapp/category_delete.html"
    success_url = reverse_lazy("admin:categories")

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


@user_passes_test(lambda u: u.is_superuser)
def products(request, pk, page="1"):
    title = "Продукты"

    category = get_object_or_404(ProductCategory, pk=pk)
    products_list = Product.objects.filter(category__pk=pk).order_by('name')

    paginator = Paginator(products_list, "2")
    try:
        products_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_paginator = paginator.page("1")
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)

    content = {
            "title": title,
            "category": category,
            "objects": products_paginator,
            "media_url": settings.MEDIA_URL,
        }

    return render(request, 'adminapp/products.html', content)


@user_passes_test(lambda u: u.is_superuser)
def product_create(request, pk):
    title = "Добавление продукта"
    category = get_object_or_404(ProductCategory, pk=pk)

    if request.method == "POST":
        product_form = ProductEditForm(request.POST, request.FILES)
        if product_form.is_valid():
            product_form.save()
            return HttpResponseRedirect(reverse("admin:products", args=[pk]))
    else:
        product_form = ProductEditForm(initial={"category": category})

    content = {"title": title, "update_form": product_form, "category": category, "media_url": settings.MEDIA_URL}
    return render(request, "adminapp/product_update.html", content)


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = "adminapp/product_read.html"


@user_passes_test(lambda u: u.is_superuser)
def product_update(request, pk):
    title = "Редактирование продукта"
    edit_product = get_object_or_404(Product, pk=pk)

    if request.method == "POST":
        edit_form = ProductEditForm(request.POST, request.FILES, instance=edit_product)
        if edit_form.is_valid():
            edit_form.save()
            return HttpResponseRedirect(reverse("admin:product_update", args=[edit_product.pk]))
    else:
        edit_form = ProductEditForm(instance=edit_product)

    content = {
        "title": title,
        "update_form": edit_form,
        "category": edit_product.category,
        "media_url": settings.MEDIA_URL,
    }
    return render(request, "adminapp/product_update.html", content)


@user_passes_test(lambda u: u.is_superuser)
def product_delete(request, pk):
    title = "Удаление продукта"

    product_to_delete = get_object_or_404(Product, pk=pk)

    if request.method == 'POST':
        product_to_delete.is_active = False
        product_to_delete.save()
        return HttpResponseRedirect(reverse('admin:products', args=[product_to_delete.category.pk]))

    content = {'title': title, 'product_to_delete': product_to_delete, "media_url": settings.MEDIA_URL}

    return render(request, 'adminapp/product_delete.html', content)

gameshop/adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title|capfirst }}
        {% endblock %}
    </title>
    
    {% block css %}
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.min.css' %}">
        <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    {% endblock %}

    {% block js %}   
    {% endblock %}
</head>

<body>
  <div class="admin_container">        
    <div class="admin_h2">Админ панель</div>
    {% block menu %}
        {% include 'adminapp/includes/inc_menu.html' %}
    {% endblock %}
           
    {% block content %}
    {% endblock %}
  </div>
</body>
</html>

gameshop/adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}

{% block content %}
  <button class="add_smth_new">
    <a href="{% url 'admin:category_create' %}">Добавить новую категорию</a>
  </button><br>

  <div class="categories_list">
    <br>
    
    {% for category in categories %}
      <div class="category_record {% if not category.is_active %}not_active{% endif %}">
        <div class="category_name">
          {{ category.name|title }}
        </div>
        <div class="category_actions">
          <button>
            <a href="{% url 'admin:products' category.pk %}">товары категории</a>
          </button>
          <button>
            <a href="{% url 'admin:category_update' category.pk %}">редактировать</a>
          </button>
          <button>
            <a href="{% url 'admin:category_delete' category.pk %}">удалить</a>
          </button>
        </div>
      </div><br>
    {% endfor%}
  </div>
{% endblock %}

gameshop/adminapp/templates/adminapp/category_delete.html
{% extends 'authnapp/base.html' %}
{% load staticfiles %}


{% block content %}
  <div class="category_delete">
    Уверены, что хотите удалить {{ category_to_delete.username }} 
    {% if category_to_delete.first_name %}
      ({{ category_to_delete.first_name|title }}</b>
      {% if category_to_delete.last_name %}
        {{ category_to_delete.last_name|title }}
      {% endif %})
    {% endif %}
    ?
    <form action="{% url 'admin:category_delete' category_to_delete.pk %}"
          method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a href="{% url 'admin:categories' %}">Отмена</a>
    </button>
  </div>
{% endblock %}

gameshop/adminapp/templates/adminapp/category_update.html
{% extends 'authnapp/base.html' %}
{% load staticfiles %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ update_form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'admin:categories' %}">В раздел категорий</a>
  </button>
{% endblock %}

gameshop/adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block content %}
<div class="product_delete">
    Уверены, что хотите удалить продукт {{ product_to_delete.name }}?
    <form action="{% url 'admin:product_delete' product_to_delete.pk %}" method="post">
        {% csrf_token %}
        <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
        <a href="{% url 'admin:products' product_to_delete.category.pk %}">Отмена</a>
    </button>
</div>
{% endblock %}

gameshop/adminapp/templates/adminapp/product_read.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block content %}
  <div class="Container">
    <div class="GameHeader">
      <div class="left"> {{ object.name }}</div>
      <div class="right">Каталог >> Игры >> {{ object.name }}</div>
    </div>
    <div class="GameReview">

        <a href="/media/{{ object.image|default:'products_images/default.jpg' }}" class="Gameimage-link">
          <img src = "/media/{{object.image|default:'products_images/default.jpg' }}" class="Gameimage">
        </a>
        
        <div>
          <p class="Game-H1">{{ object.name }}</p>
          <ul>
            <li><b>Издатель:</b> {{ object.publisher }}</li>
            <li><b>Разработчик:</b> {{ object.developer }}</li>
            <li><b>Дата выхода:</b> {{ object.released }}</li>
            <li><b>Платформа:</b> {{ object.platform }}</li>
            <li><b>Жанр:</b> {{ object.genre }}</li>
            <li><b>Язык:</b> {{ object.language }}</li>
            <li><b>Возрастной рейтинг:</b> {{ object.age }}</li>
          </ul>
          <p class="Game-H1">₽ {{ object.price }}</p>
        </div>

      </div>

      <div class="GameFeatures">
        {{ object.description }} 
      </div>

      <div class="Describe">
        <table class="GameImages">
            <tr>
              <td class="GameImages-cells"><a href="/media/{{ object.image01 }}"><img src = "/media/{{ object.image01 }}"></a></td>
              <td class="GameImages-cells"><a href="/media/{{ object.image02 }}"><img src = "/media/{{ object.image02 }}"></a></td>
              <td class="GameImages-cells"><a href="/media/{{ object.image03 }}"><img src = "/media/{{ object.image03 }}"></a></td>
            </tr>
            <tr>
              <td class="GameImages-cells"><a href="/media/{{ object.image04 }}"><img src = "/media/{{ object.image04 }}"></a></td>
              <td class="GameImages-cells"><a href="/media/{{ object.image05 }}"><img src = "/media/{{ object.image05 }}"></a></td>
              <td class="GameImages-cells"><a href="/media/{{ object.image06 }}"><img src = "/media/{{ object.image06 }}"></a></td>
            </tr>
        </table>       
      </div>
  </div>
{% endblock %}

gameshop/adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}


{% block content %}
<div class="new_category_form">
    <form class="form-horizontal" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ update_form.as_p }}
        <input class="form-control" type="submit" value="сохранить">
    </form>
    <button class="btn btn-round form-control last">
        <a href="{% url 'admin:products' category.pk %}">К списку продуктов</a>
    </button>
</div>
{% endblock %}

gameshop/adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}

{% block content %}
    <button class="add_smth_new">
      <a href="{% url 'admin:product_create' category.pk %}">новый продукт</a>
    </button><br>
    
    <div class="products_list">
       
      {% for object in objects %}
      <div class="product_record {% if not object.is_active %}not_active{% endif %}">
          <img src="{{ media_url }}{{ object.image|default:'products_images/default.jpg' }}" alt="{{ object.name }}">
          <div class="product_name">
              {{ object.name|title }}
          </div>
          <div class="product_actions">
              <button>
                  <a href="{% url 'admin:product_read' object.pk %}">подробнее</a>
              </button>
              <button>
                  <a href="{% url 'admin:product_update' object.pk %}">редактировать</a>
              </button>
              <button>
                  <a href="{% url 'admin:product_delete' object.pk %}">удалить</a>
              </button>
          </div>
          <div class="summary">
              <b>цена</b>
              <p>{{ object.price }} руб</p><br>
              <b>количество</b>
              <p>{{ object.quantity }}</p>
          </div>
      </div><br>
      {% endfor %}
      <div class="paginator">
        {% if objects.has_previous %}
          <a href="{% url 'admin:page' category.pk objects.previous_page_number %}">
            <i class="fas fa-chevron-circle-left"></i>
          </a>
        {% endif %}
        <span class="current">
          страница {{ objects.number }} из {{ objects.paginator.num_pages }}
        </span>
        {% if objects.has_next %}
          <a href="{% url 'admin:page' category.pk objects.next_page_number %}">
            <i class="fas fa-chevron-circle-left"></i>
          </a>
        {% endif %}
      </div><br>
    </div>
{% endblock %}

gameshop/adminapp/templates/adminapp/user_delete.html
{% extends 'authnapp/base.html' %}
{% load staticfiles %}


{% block content %}
  <div class="user_delete">
    Уверены, что хотите удалить {{ user_to_delete.username }} 
    {% if user_to_delete.first_name %}
      ({{ user_to_delete.first_name|title }}</b>
      {% if user_to_delete.last_name %}
        {{ user_to_delete.last_name|title }}
      {% endif %})
    {% endif %}
    ?
    <form action="{% url 'admin:user_delete' user_to_delete.pk %}"
          method="post">
      {% csrf_token %}
      <input class="btn btn-danger" type="submit" value="удалить">
    </form>
    <button class="btn btn-success">
      <a href="{% url 'admin:users' %}">
        Отмена
      </a>
    </button>
  </div>
{% endblock %}

gameshop/adminapp/templates/adminapp/user_update.html
{% extends 'authnapp/base.html' %}
{% load staticfiles %}

{% block content %}
  <form class="form-horizontal" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ update_form.as_p }}
    <input class="form-control" type="submit" value="сохранить">
  </form>
  <button class="btn btn-round form-control last">
    <a href="{% url 'admin:users' %}">
      к списку пользователей
    </a>
  </button>
{% endblock %}

gameshop/adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load staticfiles %}

{% block content %}
   <button class="add_smth_new">
      <a href="{% url 'admin:user_create' %}">Добавить нового пользователя</a>
    </button><br>
  <div class="users_list">
   
    {% for object in object_list %}
      <div class="user_record {% if not object.is_active %}not_active{% endif %}">
        <img 
          src="/media/{{ object.avatar|default:'users_avatars/default.jpg' }}"
          alt="{{ object.username }}">
        <div class="user_button">
          <button>
            <a href="{% url 'admin:user_update' object.pk %}">редактировать</a>
          </button>
          <button>
            <a href="{% url 'admin:user_delete' object.pk %}">удалить</a>
          </button>
        </div>
        <div class="user_role">
          <p>Роль: <br> 
            {% if object.is_superuser %}
              администратор
            {% else %}
              пользователь
            {% endif %}
          </p>
        </div>
        <div class="user_name">
          Имя пользователя:<br>{{ object.username }}
          <p>
            {% if object.first_name %}
              <b>{{ object.first_name|title }}</b>
                {% if object.last_name %}
                  <p>{{ object.last_name|title }}</p>
                {% endif %}
            {% endif %}
          </p>
        </div>
        <div class="user_age">
          Возраст:<br>
          {{ object.age }} лет
        </div>
        <div class="user_email">
          Почта:<br>
          {{ object.email }}
        </div>
        <div class="user_lastlogin">
          Последний вход:<br>
          {{ object.last_login }}
        </div>
      </div>
    {% endfor%}
  </div>
{% endblock %}